spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kcd
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace # SQL 바인딩 로그